title: Korte verhalen
description: korte verhalen van Stefan Zomers
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme 
- jekyll-feed
- jekyll-sitemap
url: https://stefanzomers.github.io
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
header_pages:
- about.md
