title: Korte verhalen
description: korte verhalen van Stefan Zomers
theme: leap-day
plugins:
 - jekyll-feed
 - jekyll-sitemap
url: https://stefanzomers.github.io
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
header_pages:
 - about.md
